version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - app-network

  # Backend Service
  backend:
    build:
      context: ../..
      dockerfile: ./card-app/application-docker/backend.Dockerfile
    container_name: card-app-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/card-app?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=development
    volumes:
      - ../..:/workspace
      - backend_node_modules:/workspace/card-app/node_modules
    working_dir: /workspace/card-app
    restart: unless-stopped
    networks:
      - app-network


  # Frontend Service
  frontend:
    build:
      context: ../..
      dockerfile: ./card-app/application-docker/frontend.Dockerfile
    container_name: board-app-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - PORT=3001
    volumes:
      - ../..:/workspace
      - frontend_node_modules:/workspace/board-app/node_modules
    working_dir: /workspace/board-app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  app-network:
    driver: bridge
